model = "gpt-5.4"
model_reasoning_effort = "medium"
[projects."/Users/juniq/ai-agent"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/juniqlim/growterm"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/juniqlim/resume"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/juniqlim"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/juniqlim/think"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/juniqlim/PostureAlarm"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/other/openai-python"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/mediquitous/zelda"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/other"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/other/egovframe-template-simple-react"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/juniqlim/note"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/other/openai-python-2"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/juniqlim/dotfiles"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/others"]
trust_level = "trusted"

[projects."/Users/juniq/develop/code/juniqlim/minimal-symlayer-keyboard"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"

[tui]
status_line = ["current-dir", "context-remaining", "five-hour-limit", "weekly-limit", "model-with-reasoning"]

[plugins."github@openai-curated"]
enabled = true
